### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by dclardy64** [DEFENDORe/splitflap-remote#1]
Following the instructions in the readme, but it is throwing an error about not being able to find the file below.

npm ERR! path /../../git/splitflap-remote/splitflap/software/chainlink/js/packages/splitflapjs-core/package.json

From the other repo from Scott, it appears that I need to clone the repo inside of your repo. Is that the correct thing to do?

**Comment by dclardy64** [comment]
It looks like my machine was having an issue.

**Comment by DEFENDORe** [comment]
Glad you got it working! Just for a heads up, the package.json file has a "preinstall" script that should fetch and build the javascript libraries from scotts repo.
